// Package providerexchange implements the privacy-minimal cryptographic
// envelope used by the Not Human Search provider exchange.
//
// The signed payloads intentionally contain only NHS-generated opaque UUIDs,
// controlled enums, timestamps, and commercial accounting fields. They have no
// extension map or free-text field where a raw query, contact detail, network
// identifier, or claimed agent/principal identity could be placed.
package providerexchange

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
	"time"
)

const (
	// AttributionTokenVersion is the only attribution-token version accepted by
	// this package. Version changes must use a new signing domain.
	AttributionTokenVersion = 1

	// OutcomeReceiptVersion is the only outcome-receipt version accepted by
	// this package. Version changes must use a new signing domain.
	OutcomeReceiptVersion = 1

	// CommercialProofManifestVersion is the only privacy-redacted commercial
	// proof manifest accepted by this package. It has an independent signing
	// domain: an attribution or outcome signature can never authenticate it.
	CommercialProofManifestVersion     = 1
	DefaultSigningKeyID                = "nhs-provider-signing-v1"
	CommercialProofManifestContractV1  = "nhs-provider-proof-manifest-v1"
	CommercialProofMarketPolicyV1      = "nhs-free-organic-provider-funded-v1"
	CommercialProofReviewEvidenceV1    = "nhs-provider-proof-review-root-v1"
	CommercialProofVerificationScopeV1 = "nhs-private-keyring"
	CommercialProofManifestScopeV1     = "NHS-recorded exact closed-pilot aggregate; HMAC-signed and verifiable only by NHS; not independent proof of provider truth, cash collection, or agent identity."

	// AllowedClockSkew tolerates small clock differences while still rejecting
	// tokens and receipts whose trusted timestamp is materially in the future.
	AllowedClockSkew = 2 * time.Minute

	maxCompactTokenBytes      = 4096
	nonceBytes                = 24
	maxPreviousSigningKeys    = 64
	minimumSigningSecretBytes = 32

	keyDerivationDomain = "nothumansearch/provider-exchange/key-derivation/v1"
	attributionDomain   = "nothumansearch/provider-exchange/attribution-token/v1"
	outcomeDomain       = "nothumansearch/provider-exchange/outcome-receipt/v1"
	proofManifestDomain = "nothumansearch/provider-exchange/commercial-proof-manifest/v1"
)

var (
	ErrSecretRequired   = errors.New("provider exchange signing secret required")
	ErrInvalidClaims    = errors.New("invalid signed claims")
	ErrMalformed        = errors.New("malformed signed value")
	ErrInvalidSignature = errors.New("invalid signature")
	ErrUnknownKeyID     = errors.New("unknown provider exchange signing key")
	ErrExpired          = errors.New("signed value expired")
	ErrNotYetValid      = errors.New("signed value is not yet valid")
)

// Outcome is a controlled provider-reported result. It cannot carry free text.
type Outcome string

const (
	OutcomeAccepted  Outcome = "accepted"
	OutcomeActivated Outcome = "activated"
	OutcomeConverted Outcome = "converted"
	OutcomeRejected  Outcome = "rejected"
	OutcomeDuplicate Outcome = "duplicate"
	OutcomeInvalid   Outcome = "invalid"
)

// ChargeStatus says how ChargedMinor affected the provider account. The amount
// is always non-negative; the status supplies the direction.
type ChargeStatus string

const (
	ChargeStatusCharged  ChargeStatus = "charged"
	ChargeStatusCredited ChargeStatus = "credited"
	ChargeStatusNone     ChargeStatus = "none"
)

// AttributionClaims is the complete attribution-token payload. TicketID and
// OfferID must be canonical UUIDs generated by NHS storage. Nonce is random,
// URL-safe entropy and must not be derived from a person, query, request, IP,
// user agent, or alleged agent identity. Times are Unix seconds in UTC.
type AttributionClaims struct {
	Version   int    `json:"v"`
	KeyID     string `json:"kid"`
	TicketID  string `json:"ticket_id"`
	OfferID   string `json:"offer_id"`
	IssuedAt  int64  `json:"issued_at"`
	ExpiresAt int64  `json:"expires_at"`
	Nonce     string `json:"nonce"`
}

// OutcomeReceipt is the complete signed receipt payload. ReceiptID,
// ProviderEventID, TicketID, and OfferID must be NHS-generated canonical UUIDs;
// raw provider idempotency keys must be hashed or mapped to an NHS UUID before
// this type is populated. Currency is an ISO-4217 alpha-3 code in lowercase.
// Times are Unix seconds in UTC.
type OutcomeReceipt struct {
	Version            int          `json:"v"`
	KeyID              string       `json:"kid"`
	ReceiptID          string       `json:"receipt_id"`
	TicketID           string       `json:"ticket_id"`
	OfferID            string       `json:"offer_id"`
	NHSEventID         string       `json:"nhs_event_id"`
	Outcome            Outcome      `json:"outcome"`
	ProviderReportedAt int64        `json:"provider_reported_at"`
	RecordedAt         int64        `json:"recorded_at"`
	ExpiresAt          int64        `json:"expires_at"`
	ChargedMinor       int64        `json:"charged_minor"`
	Currency           string       `json:"currency"`
	ChargeStatus       ChargeStatus `json:"charge_status"`
}

// CommercialProofReviewCount reports aggregate owner-review coverage without
// exposing any provider, offer, ticket, handoff, callback, principal, or agent
// identifier. An issuable manifest requires Valid == Required for every
// category.
type CommercialProofReviewCount struct {
	Required int `json:"required"`
	Valid    int `json:"valid"`
}

// CommercialProofReviewCoverage is deliberately fixed-shape. It has no map or
// extension field where row-level or free-form information can be inserted.
type CommercialProofReviewCoverage struct {
	Providers CommercialProofReviewCount `json:"providers"`
	Offers    CommercialProofReviewCount `json:"offers"`
	Tickets   CommercialProofReviewCount `json:"tickets"`
	Handoffs  CommercialProofReviewCount `json:"handoffs"`
	Callbacks CommercialProofReviewCount `json:"callbacks"`
}

// CommercialProofCurrencyAmount is a canonical aggregate accounting bucket.
// Callers must sort buckets by Currency and omit zero amounts.
type CommercialProofCurrencyAmount struct {
	Currency    string `json:"currency"`
	AmountMinor int64  `json:"amount_minor"`
}

// CommercialProofManifest is the complete signed, privacy-redacted statement
// NHS can issue for one exact closed pilot. It contains aggregate counters and
// controlled contract fields only. It deliberately excludes company/provider
// IDs, offer/ticket/handoff/callback IDs, raw queries, search receipts, bearer
// material, principal or agent identity, and owner evidence references.
type CommercialProofManifest struct {
	Version                           int                             `json:"v"`
	KeyID                             string                          `json:"kid"`
	SignatureVerificationScope        string                          `json:"signature_verification_scope"`
	ManifestContractVersion           string                          `json:"manifest_contract_version"`
	ManifestID                        string                          `json:"manifest_id"`
	ProviderPilotEpochID              string                          `json:"provider_pilot_epoch_id"`
	ProviderPilotContractVersion      string                          `json:"provider_pilot_contract_version"`
	ReviewContractVersion             string                          `json:"review_contract_version"`
	ReviewEvidenceContractVersion     string                          `json:"review_evidence_contract_version"`
	MarketPolicyContractVersion       string                          `json:"market_policy_contract_version"`
	ProofSnapshotSHA256               string                          `json:"proof_snapshot_sha256"`
	ReviewEvidenceSHA256              string                          `json:"review_evidence_sha256"`
	PilotDemandTopic                  string                          `json:"pilot_demand_topic"`
	PilotStatus                       string                          `json:"pilot_status"`
	IssuedAt                          int64                           `json:"issued_at"`
	OutcomeReceiptIntegrityValid      bool                            `json:"outcome_receipt_integrity_valid"`
	ReviewIntegrityValid              bool                            `json:"review_integrity_valid"`
	VerifiedOutcomeReceipts           int                             `json:"verified_outcome_receipts"`
	RejectedOutcomeReceipts           int                             `json:"rejected_outcome_receipts"`
	VerifiedOutcomeLedgerEntries      int                             `json:"verified_outcome_ledger_entries"`
	RejectedOutcomeLedgerEntries      int                             `json:"rejected_outcome_ledger_entries"`
	VerifiedProviderCompanies         int                             `json:"verified_provider_companies"`
	VerifiedProviderAcceptedHandoffs  int                             `json:"verified_provider_accepted_handoffs"`
	VerifiedProviderActivations       int                             `json:"verified_provider_confirmed_activations"`
	VerifiedProviderRenewals          int                             `json:"verified_provider_renewals"`
	VerifiedProviderConversions       int                             `json:"verified_provider_confirmed_conversions"`
	ReviewCoverage                    CommercialProofReviewCoverage   `json:"review_coverage"`
	MonetaryAmountsWithheldForPrivacy bool                            `json:"monetary_amounts_withheld_for_privacy"`
	VerifiedPrepaidSettled            []CommercialProofCurrencyAmount `json:"verified_prepaid_settled"`
	VerifiedPrepaidNetDebited         []CommercialProofCurrencyAmount `json:"verified_prepaid_net_debited"`
	VerifiedTermsNetReceivable        []CommercialProofCurrencyAmount `json:"verified_terms_net_receivable"`
	PilotThresholdsMet                bool                            `json:"pilot_thresholds_met"`
	OrganicRankSold                   bool                            `json:"organic_rank_sold"`
	RawQueriesSold                    bool                            `json:"raw_queries_sold"`
	AgentIdentitiesSold               bool                            `json:"agent_identities_sold"`
	EvidenceScope                     string                          `json:"evidence_scope"`
}

type signingKeyMaterial struct {
	attributionKey   [sha256.Size]byte
	outcomeKey       [sha256.Size]byte
	proofManifestKey [sha256.Size]byte
}

// Signer derives independent attribution, outcome, and commercial-proof
// manifest keys from a dedicated provider-exchange signing secret. A bounded
// keyring lets a rotated active key coexist with retained previous keys, so
// outstanding tickets and historical proofs do not silently fail verification
// after rotation.
type Signer struct {
	activeKeyID string
	keys        map[string]signingKeyMaterial
}

// NewSigner is the single-key constructor used by focused tests and simple
// deployments. Production can use NewSignerKeyring to retain previous keys.
func NewSigner(secret string) (*Signer, error) {
	return NewSignerKeyring(DefaultSigningKeyID, secret, nil)
}

// NewSignerKeyring constructs a signer with one active key and a bounded set of
// previous verification keys. Production startup separately rejects removal of
// any key ID still referenced by an attribution token or outcome receipt. Key
// IDs are public version labels; secret values are never retained after
// domain-specific subkeys are derived.
func NewSignerKeyring(activeKeyID, activeSecret string, previous map[string]string) (*Signer, error) {
	activeKeyID = strings.TrimSpace(activeKeyID)
	if !isKeyID(activeKeyID) || len([]byte(activeSecret)) < minimumSigningSecretBytes || strings.TrimSpace(activeSecret) == "" {
		return nil, ErrSecretRequired
	}
	if len(previous) > maxPreviousSigningKeys {
		return nil, fmt.Errorf("%w: too many previous signing keys", ErrInvalidClaims)
	}
	keys := make(map[string]signingKeyMaterial, len(previous)+1)
	add := func(keyID, secret string) error {
		keyID = strings.TrimSpace(keyID)
		if !isKeyID(keyID) || len([]byte(secret)) < minimumSigningSecretBytes || strings.TrimSpace(secret) == "" {
			return ErrSecretRequired
		}
		if _, exists := keys[keyID]; exists {
			return fmt.Errorf("%w: duplicate signing key id", ErrInvalidClaims)
		}
		keys[keyID] = signingKeyMaterial{
			attributionKey:   deriveKey([]byte(secret), attributionDomain),
			outcomeKey:       deriveKey([]byte(secret), outcomeDomain),
			proofManifestKey: deriveKey([]byte(secret), proofManifestDomain),
		}
		return nil
	}
	if err := add(activeKeyID, activeSecret); err != nil {
		return nil, err
	}
	for keyID, secret := range previous {
		if err := add(keyID, secret); err != nil {
			return nil, err
		}
	}
	return &Signer{activeKeyID: activeKeyID, keys: keys}, nil
}

func (s *Signer) ActiveKeyID() string {
	if s == nil {
		return ""
	}
	return s.activeKeyID
}

// SupportsKeyID reports only whether verification material for a public key ID
// is loaded. It never exposes derived or configured secret material.
func (s *Signer) SupportsKeyID(keyID string) bool {
	if s == nil {
		return false
	}
	_, ok := s.keys[strings.TrimSpace(keyID)]
	return ok
}

// NewNonce returns random URL-safe entropy suitable for AttributionClaims.
// It contains no padding and is independent of request or user data.
func NewNonce() (string, error) {
	raw := make([]byte, nonceBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate attribution nonce: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// NewAttributionClaims creates the fixed attribution payload and a random
// nonce. The caller chooses a short, purpose-appropriate expiry.
func NewAttributionClaims(ticketID, offerID string, issuedAt, expiresAt time.Time) (AttributionClaims, error) {
	return NewAttributionClaimsForKey(DefaultSigningKeyID, ticketID, offerID, issuedAt, expiresAt)
}

func NewAttributionClaimsForKey(keyID, ticketID, offerID string, issuedAt, expiresAt time.Time) (AttributionClaims, error) {
	nonce, err := NewNonce()
	if err != nil {
		return AttributionClaims{}, err
	}
	claims := AttributionClaims{
		Version:   AttributionTokenVersion,
		KeyID:     strings.TrimSpace(keyID),
		TicketID:  ticketID,
		OfferID:   offerID,
		IssuedAt:  issuedAt.Unix(),
		ExpiresAt: expiresAt.Unix(),
		Nonce:     nonce,
	}
	if err := validateAttributionStructure(claims); err != nil {
		return AttributionClaims{}, err
	}
	return claims, nil
}

// SignAttribution returns base64url(payload) + "." + base64url(HMAC). The
// result is safe to place in an action URL query parameter without padding.
func (s *Signer) SignAttribution(claims AttributionClaims) (string, error) {
	if s == nil {
		return "", ErrSecretRequired
	}
	if claims.KeyID == "" {
		claims.KeyID = s.activeKeyID
	}
	keys, ok := s.keys[claims.KeyID]
	if !ok {
		return "", ErrUnknownKeyID
	}
	payload, err := canonicalAttribution(claims)
	if err != nil {
		return "", err
	}
	signature := signMAC(keys.attributionKey, attributionDomain, payload)
	return claims.KeyID + "." + base64.RawURLEncoding.EncodeToString(payload) + "." +
		base64.RawURLEncoding.EncodeToString(signature[:]), nil
}

// VerifyAttribution verifies the immutable claims and then applies their short
// authorization window. Callers must separately enforce ticket state and
// outcome idempotency.
func (s *Signer) VerifyAttribution(token string, now time.Time) (AttributionClaims, error) {
	claims, err := s.VerifyAttributionSignature(token)
	if err != nil {
		return AttributionClaims{}, err
	}
	if err := validateAttributionTime(claims, now); err != nil {
		return AttributionClaims{}, err
	}
	return claims, nil
}

// VerifyAttributionSignature authenticates immutable attribution claims but
// deliberately does not apply their authorization window. This is only for
// resolving an already charged ticket with a later invalid/duplicate credit;
// it must never authorize a redirect, positive outcome, or new charge.
func (s *Signer) VerifyAttributionSignature(token string) (AttributionClaims, error) {
	if s == nil {
		return AttributionClaims{}, ErrSecretRequired
	}
	keyID, payload, providedMAC, err := splitCompactToken(token)
	if err != nil {
		return AttributionClaims{}, err
	}
	keys, ok := s.keys[keyID]
	if !ok {
		return AttributionClaims{}, ErrUnknownKeyID
	}
	expectedMAC := signMAC(keys.attributionKey, attributionDomain, payload)
	if subtle.ConstantTimeCompare(providedMAC, expectedMAC[:]) != 1 {
		return AttributionClaims{}, ErrInvalidSignature
	}
	var claims AttributionClaims
	if err := decodeCanonicalJSON(payload, &claims); err != nil {
		return AttributionClaims{}, err
	}
	if claims.KeyID != keyID {
		return AttributionClaims{}, ErrInvalidSignature
	}
	canonical, err := canonicalAttribution(claims)
	if err != nil {
		return AttributionClaims{}, err
	}
	if !bytes.Equal(payload, canonical) {
		return AttributionClaims{}, fmt.Errorf("%w: non-canonical attribution payload", ErrMalformed)
	}
	return claims, nil
}

// CanonicalOutcomeReceipt returns the exact deterministic bytes covered by an
// outcome signature. Field order is the OutcomeReceipt declaration order;
// values are compact JSON with no whitespace or trailing newline.
func CanonicalOutcomeReceipt(receipt OutcomeReceipt) ([]byte, error) {
	if err := validateOutcomeStructure(receipt); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(receipt)
	if err != nil {
		return nil, fmt.Errorf("%w: encode outcome receipt: %v", ErrMalformed, err)
	}
	return payload, nil
}

// SignOutcomeReceipt returns canonical receipt JSON and its unpadded base64url
// signature separately so both can be persisted after transaction-derived
// charging fields are known.
func (s *Signer) SignOutcomeReceipt(receipt OutcomeReceipt) (canonical string, signature string, err error) {
	if s == nil {
		return "", "", ErrSecretRequired
	}
	if receipt.KeyID == "" {
		receipt.KeyID = s.activeKeyID
	}
	keys, ok := s.keys[receipt.KeyID]
	if !ok {
		return "", "", ErrUnknownKeyID
	}
	payload, err := CanonicalOutcomeReceipt(receipt)
	if err != nil {
		return "", "", err
	}
	mac := signMAC(keys.outcomeKey, outcomeDomain, payload)
	return string(payload), base64.RawURLEncoding.EncodeToString(mac[:]), nil
}

// VerifyOutcomeReceipt authenticates a canonical receipt in constant time,
// rejects added/unknown fields and non-canonical JSON, then applies expiry and
// future-timestamp checks.
func (s *Signer) VerifyOutcomeReceipt(canonical, signature string, now time.Time) (OutcomeReceipt, error) {
	receipt, err := s.VerifyOutcomeReceiptSignature(canonical, signature)
	if err != nil {
		return OutcomeReceipt{}, err
	}
	if err := validateOutcomeTime(receipt, now); err != nil {
		return OutcomeReceipt{}, err
	}
	return receipt, nil
}

// VerifyOutcomeReceiptSignature authenticates immutable receipt contents but
// deliberately does not apply the receipt freshness window. Public callers can
// report cryptographic validity separately from freshness and current online
// ticket/accounting state.
func (s *Signer) VerifyOutcomeReceiptSignature(canonical, signature string) (OutcomeReceipt, error) {
	if s == nil {
		return OutcomeReceipt{}, ErrSecretRequired
	}
	if len(canonical) == 0 || len(canonical) > maxCompactTokenBytes {
		return OutcomeReceipt{}, ErrMalformed
	}
	providedMAC, err := base64.RawURLEncoding.Strict().DecodeString(signature)
	if err != nil || len(providedMAC) != sha256.Size {
		return OutcomeReceipt{}, ErrMalformed
	}
	payload := []byte(canonical)
	var receipt OutcomeReceipt
	if err := decodeCanonicalJSON(payload, &receipt); err != nil {
		return OutcomeReceipt{}, err
	}
	keys, ok := s.keys[receipt.KeyID]
	if !ok {
		return OutcomeReceipt{}, ErrUnknownKeyID
	}
	expectedMAC := signMAC(keys.outcomeKey, outcomeDomain, payload)
	if subtle.ConstantTimeCompare(providedMAC, expectedMAC[:]) != 1 {
		return OutcomeReceipt{}, ErrInvalidSignature
	}
	reencoded, err := CanonicalOutcomeReceipt(receipt)
	if err != nil {
		return OutcomeReceipt{}, err
	}
	if !bytes.Equal(payload, reencoded) {
		return OutcomeReceipt{}, fmt.Errorf("%w: non-canonical outcome receipt", ErrMalformed)
	}
	return receipt, nil
}

// CanonicalCommercialProofManifest returns the exact deterministic bytes
// covered by a proof-manifest signature. Struct declaration order fixes field
// order; currency buckets must already be sorted and unique.
func CanonicalCommercialProofManifest(manifest CommercialProofManifest) ([]byte, error) {
	if err := validateCommercialProofManifestStructure(manifest); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("%w: encode commercial proof manifest: %v", ErrMalformed, err)
	}
	if len(payload) > maxCompactTokenBytes*4 {
		return nil, fmt.Errorf("%w: commercial proof manifest is too large", ErrMalformed)
	}
	return payload, nil
}

// SignCommercialProofManifest signs a final aggregate proof statement under a
// dedicated domain and returns canonical JSON plus an unpadded base64url MAC.
func (s *Signer) SignCommercialProofManifest(manifest CommercialProofManifest) (canonical string, signature string, err error) {
	if s == nil {
		return "", "", ErrSecretRequired
	}
	if manifest.KeyID == "" {
		manifest.KeyID = s.activeKeyID
	}
	keys, ok := s.keys[manifest.KeyID]
	if !ok {
		return "", "", ErrUnknownKeyID
	}
	payload, err := CanonicalCommercialProofManifest(manifest)
	if err != nil {
		return "", "", err
	}
	mac := signMAC(keys.proofManifestKey, proofManifestDomain, payload)
	return string(payload), base64.RawURLEncoding.EncodeToString(mac[:]), nil
}

// VerifyCommercialProofManifest authenticates a canonical manifest and
// rejects a materially future NHS issue time. Manifests do not expire: they
// are immutable historical statements for an exact closed pilot.
func (s *Signer) VerifyCommercialProofManifest(canonical, signature string, now time.Time) (CommercialProofManifest, error) {
	manifest, err := s.VerifyCommercialProofManifestSignature(canonical, signature)
	if err != nil {
		return CommercialProofManifest{}, err
	}
	if now.IsZero() {
		return CommercialProofManifest{}, fmt.Errorf("%w: verification time required", ErrInvalidClaims)
	}
	if manifest.IssuedAt > now.Add(AllowedClockSkew).Unix() {
		return CommercialProofManifest{}, ErrNotYetValid
	}
	return manifest, nil
}

// VerifyCommercialProofManifestSignature verifies immutable historical proof
// without applying a wall-clock freshness decision.
func (s *Signer) VerifyCommercialProofManifestSignature(canonical, signature string) (CommercialProofManifest, error) {
	if s == nil {
		return CommercialProofManifest{}, ErrSecretRequired
	}
	if len(canonical) == 0 || len(canonical) > maxCompactTokenBytes*4 {
		return CommercialProofManifest{}, ErrMalformed
	}
	providedMAC, err := base64.RawURLEncoding.Strict().DecodeString(signature)
	if err != nil || len(providedMAC) != sha256.Size {
		return CommercialProofManifest{}, ErrMalformed
	}
	payload := []byte(canonical)
	var manifest CommercialProofManifest
	if err := decodeCanonicalJSON(payload, &manifest); err != nil {
		return CommercialProofManifest{}, err
	}
	keys, ok := s.keys[manifest.KeyID]
	if !ok {
		return CommercialProofManifest{}, ErrUnknownKeyID
	}
	expectedMAC := signMAC(keys.proofManifestKey, proofManifestDomain, payload)
	if subtle.ConstantTimeCompare(providedMAC, expectedMAC[:]) != 1 {
		return CommercialProofManifest{}, ErrInvalidSignature
	}
	reencoded, err := CanonicalCommercialProofManifest(manifest)
	if err != nil {
		return CommercialProofManifest{}, err
	}
	if !bytes.Equal(payload, reencoded) {
		return CommercialProofManifest{}, fmt.Errorf("%w: non-canonical commercial proof manifest", ErrMalformed)
	}
	return manifest, nil
}

func validateCommercialProofManifestStructure(manifest CommercialProofManifest) error {
	if manifest.Version != CommercialProofManifestVersion ||
		manifest.ManifestContractVersion != CommercialProofManifestContractV1 ||
		manifest.ProviderPilotContractVersion != "nhs-provider-pilot-v1" ||
		manifest.ReviewContractVersion != "nhs-provider-pilot-review-v1" ||
		manifest.ReviewEvidenceContractVersion != CommercialProofReviewEvidenceV1 ||
		manifest.MarketPolicyContractVersion != CommercialProofMarketPolicyV1 {
		return fmt.Errorf("%w: invalid commercial proof contract", ErrInvalidClaims)
	}
	if !isKeyID(manifest.KeyID) || !isCanonicalUUID(manifest.ManifestID) ||
		!isCanonicalUUID(manifest.ProviderPilotEpochID) ||
		!isSHA256Hex(manifest.ProofSnapshotSHA256) ||
		!isSHA256Hex(manifest.ReviewEvidenceSHA256) {
		return fmt.Errorf("%w: invalid commercial proof identity", ErrInvalidClaims)
	}
	if !commercialProofDemandTopics[manifest.PilotDemandTopic] ||
		manifest.PilotStatus != "closed" || manifest.IssuedAt <= 0 {
		return fmt.Errorf("%w: invalid commercial proof pilot scope", ErrInvalidClaims)
	}
	if !manifest.OutcomeReceiptIntegrityValid || !manifest.ReviewIntegrityValid ||
		!manifest.PilotThresholdsMet || manifest.OrganicRankSold ||
		manifest.RawQueriesSold || manifest.AgentIdentitiesSold ||
		manifest.SignatureVerificationScope != CommercialProofVerificationScopeV1 ||
		manifest.EvidenceScope != CommercialProofManifestScopeV1 {
		return fmt.Errorf("%w: commercial proof is not issuable", ErrInvalidClaims)
	}
	counts := []int{
		manifest.VerifiedOutcomeReceipts,
		manifest.RejectedOutcomeReceipts,
		manifest.VerifiedOutcomeLedgerEntries,
		manifest.RejectedOutcomeLedgerEntries,
		manifest.VerifiedProviderCompanies,
		manifest.VerifiedProviderAcceptedHandoffs,
		manifest.VerifiedProviderActivations,
		manifest.VerifiedProviderRenewals,
		manifest.VerifiedProviderConversions,
	}
	for _, count := range counts {
		if count < 0 {
			return fmt.Errorf("%w: negative commercial proof count", ErrInvalidClaims)
		}
	}
	if manifest.VerifiedProviderCompanies < 3 ||
		manifest.VerifiedProviderAcceptedHandoffs < 5 ||
		manifest.VerifiedProviderActivations < 2 ||
		manifest.VerifiedProviderRenewals < 1 {
		return fmt.Errorf("%w: commercial proof thresholds are not met", ErrInvalidClaims)
	}
	if manifest.RejectedOutcomeReceipts != 0 || manifest.RejectedOutcomeLedgerEntries != 0 {
		return fmt.Errorf("%w: commercial proof contains rejected integrity evidence", ErrInvalidClaims)
	}
	if manifest.VerifiedProviderRenewals > manifest.VerifiedProviderCompanies ||
		manifest.VerifiedProviderAcceptedHandoffs > manifest.VerifiedOutcomeReceipts ||
		manifest.VerifiedProviderActivations > manifest.VerifiedProviderAcceptedHandoffs ||
		manifest.VerifiedProviderConversions > manifest.VerifiedProviderActivations ||
		manifest.VerifiedOutcomeLedgerEntries > manifest.VerifiedOutcomeReceipts {
		return fmt.Errorf("%w: inconsistent commercial proof outcome aggregates", ErrInvalidClaims)
	}
	reviews := []CommercialProofReviewCount{
		manifest.ReviewCoverage.Providers,
		manifest.ReviewCoverage.Offers,
		manifest.ReviewCoverage.Tickets,
		manifest.ReviewCoverage.Handoffs,
		manifest.ReviewCoverage.Callbacks,
	}
	for _, review := range reviews {
		if review.Required <= 0 || review.Valid != review.Required {
			return fmt.Errorf("%w: incomplete commercial proof review coverage", ErrInvalidClaims)
		}
	}
	if manifest.ReviewCoverage.Providers.Required != manifest.VerifiedProviderCompanies ||
		manifest.ReviewCoverage.Offers.Required < manifest.VerifiedProviderCompanies ||
		manifest.ReviewCoverage.Tickets.Required < manifest.VerifiedProviderAcceptedHandoffs ||
		manifest.ReviewCoverage.Handoffs.Required != manifest.ReviewCoverage.Tickets.Required ||
		manifest.ReviewCoverage.Callbacks.Required != manifest.VerifiedOutcomeReceipts {
		return fmt.Errorf("%w: inconsistent commercial proof review coverage", ErrInvalidClaims)
	}
	if !manifest.MonetaryAmountsWithheldForPrivacy ||
		manifest.VerifiedPrepaidSettled == nil ||
		manifest.VerifiedPrepaidNetDebited == nil ||
		manifest.VerifiedTermsNetReceivable == nil ||
		len(manifest.VerifiedPrepaidSettled) != 0 ||
		len(manifest.VerifiedPrepaidNetDebited) != 0 ||
		len(manifest.VerifiedTermsNetReceivable) != 0 {
		return fmt.Errorf("%w: commercial proof currency aggregates must be arrays", ErrInvalidClaims)
	}
	if err := validateCommercialProofCurrencyAmounts(manifest.VerifiedPrepaidSettled); err != nil {
		return err
	}
	for _, amount := range manifest.VerifiedPrepaidSettled {
		if amount.AmountMinor < 0 {
			return fmt.Errorf("%w: prepaid settlement aggregate cannot be negative", ErrInvalidClaims)
		}
	}
	if err := validateCommercialProofCurrencyAmounts(manifest.VerifiedPrepaidNetDebited); err != nil {
		return err
	}
	if err := validateCommercialProofCurrencyAmounts(manifest.VerifiedTermsNetReceivable); err != nil {
		return err
	}
	return nil
}

func validateCommercialProofCurrencyAmounts(amounts []CommercialProofCurrencyAmount) error {
	previous := ""
	for _, amount := range amounts {
		if len(amount.Currency) != 3 || amount.Currency <= previous || amount.AmountMinor == 0 {
			return fmt.Errorf("%w: invalid commercial proof currency aggregate", ErrInvalidClaims)
		}
		for i := 0; i < len(amount.Currency); i++ {
			if amount.Currency[i] < 'a' || amount.Currency[i] > 'z' {
				return fmt.Errorf("%w: invalid commercial proof currency aggregate", ErrInvalidClaims)
			}
		}
		previous = amount.Currency
	}
	return nil
}

var commercialProofDemandTopics = map[string]bool{
	"payments": true, "commerce": true, "jobs": true, "data": true,
	"search": true, "weather": true, "maps": true, "email": true,
	"messaging": true, "image": true, "video": true, "audio": true,
	"documents": true, "security": true, "finance": true, "health": true,
	"education": true, "news": true, "analytics": true, "automation": true,
	"productivity": true, "identity": true, "storage": true, "ai-tools": true,
	"developer-tools": true,
}

func isSHA256Hex(value string) bool {
	if len(value) != sha256.Size*2 {
		return false
	}
	for i := 0; i < len(value); i++ {
		if value[i] >= '0' && value[i] <= '9' || value[i] >= 'a' && value[i] <= 'f' {
			continue
		}
		return false
	}
	return true
}

func canonicalAttribution(claims AttributionClaims) ([]byte, error) {
	if err := validateAttributionStructure(claims); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(claims)
	if err != nil {
		return nil, fmt.Errorf("%w: encode attribution claims: %v", ErrMalformed, err)
	}
	return payload, nil
}

func validateAttributionStructure(claims AttributionClaims) error {
	if claims.Version != AttributionTokenVersion {
		return fmt.Errorf("%w: unsupported attribution version", ErrInvalidClaims)
	}
	if !isKeyID(claims.KeyID) {
		return fmt.Errorf("%w: invalid attribution key id", ErrInvalidClaims)
	}
	if !isCanonicalUUID(claims.TicketID) || !isCanonicalUUID(claims.OfferID) {
		return fmt.Errorf("%w: attribution IDs must be canonical UUIDs", ErrInvalidClaims)
	}
	if claims.IssuedAt <= 0 || claims.ExpiresAt <= claims.IssuedAt {
		return fmt.Errorf("%w: invalid attribution validity window", ErrInvalidClaims)
	}
	if !isBase64URLNonce(claims.Nonce) {
		return fmt.Errorf("%w: invalid attribution nonce", ErrInvalidClaims)
	}
	return nil
}

func validateAttributionTime(claims AttributionClaims, now time.Time) error {
	if now.IsZero() {
		return fmt.Errorf("%w: verification time required", ErrInvalidClaims)
	}
	nowUnix := now.Unix()
	if claims.IssuedAt > now.Add(AllowedClockSkew).Unix() {
		return ErrNotYetValid
	}
	if nowUnix >= claims.ExpiresAt {
		return ErrExpired
	}
	return nil
}

func validateOutcomeStructure(receipt OutcomeReceipt) error {
	if receipt.Version != OutcomeReceiptVersion {
		return fmt.Errorf("%w: unsupported outcome receipt version", ErrInvalidClaims)
	}
	if !isKeyID(receipt.KeyID) {
		return fmt.Errorf("%w: invalid outcome key id", ErrInvalidClaims)
	}
	if !isCanonicalUUID(receipt.ReceiptID) ||
		!isCanonicalUUID(receipt.TicketID) ||
		!isCanonicalUUID(receipt.OfferID) ||
		!isCanonicalUUID(receipt.NHSEventID) {
		return fmt.Errorf("%w: outcome IDs must be canonical UUIDs", ErrInvalidClaims)
	}
	if !validOutcome(receipt.Outcome) {
		return fmt.Errorf("%w: unsupported outcome", ErrInvalidClaims)
	}
	if receipt.ProviderReportedAt <= 0 || receipt.RecordedAt <= 0 || receipt.ExpiresAt <= receipt.RecordedAt {
		return fmt.Errorf("%w: invalid outcome validity window", ErrInvalidClaims)
	}
	if receipt.ProviderReportedAt > receipt.RecordedAt+int64(AllowedClockSkew/time.Second) {
		return fmt.Errorf("%w: provider report occurs after recording", ErrInvalidClaims)
	}
	if receipt.ChargedMinor < 0 {
		return fmt.Errorf("%w: charged_minor must be non-negative", ErrInvalidClaims)
	}
	if receipt.Currency != "usd" {
		return fmt.Errorf("%w: pilot receipt currency must be usd", ErrInvalidClaims)
	}
	switch receipt.ChargeStatus {
	case ChargeStatusCharged, ChargeStatusCredited:
		if receipt.ChargedMinor == 0 {
			return fmt.Errorf("%w: charged or credited receipt requires a positive amount", ErrInvalidClaims)
		}
	case ChargeStatusNone:
		if receipt.ChargedMinor != 0 {
			return fmt.Errorf("%w: uncharged receipt must have zero charged_minor", ErrInvalidClaims)
		}
	default:
		return fmt.Errorf("%w: unsupported charge_status", ErrInvalidClaims)
	}
	return nil
}

func validateOutcomeTime(receipt OutcomeReceipt, now time.Time) error {
	if now.IsZero() {
		return fmt.Errorf("%w: verification time required", ErrInvalidClaims)
	}
	latestAllowed := now.Add(AllowedClockSkew).Unix()
	if receipt.RecordedAt > latestAllowed || receipt.ProviderReportedAt > latestAllowed {
		return ErrNotYetValid
	}
	if now.Unix() >= receipt.ExpiresAt {
		return ErrExpired
	}
	return nil
}

func validOutcome(outcome Outcome) bool {
	switch outcome {
	case OutcomeAccepted, OutcomeActivated, OutcomeConverted, OutcomeRejected, OutcomeDuplicate, OutcomeInvalid:
		return true
	default:
		return false
	}
}

func isCanonicalUUID(value string) bool {
	if len(value) != 36 {
		return false
	}
	for i := 0; i < len(value); i++ {
		switch i {
		case 8, 13, 18, 23:
			if value[i] != '-' {
				return false
			}
		default:
			if !((value[i] >= '0' && value[i] <= '9') || (value[i] >= 'a' && value[i] <= 'f')) {
				return false
			}
		}
	}
	return true
}

func isBase64URLNonce(value string) bool {
	if len(value) != base64.RawURLEncoding.EncodedLen(nonceBytes) {
		return false
	}
	raw, err := base64.RawURLEncoding.Strict().DecodeString(value)
	return err == nil && len(raw) == nonceBytes
}

func isKeyID(value string) bool {
	if len(value) < 3 || len(value) > 64 {
		return false
	}
	for i := 0; i < len(value); i++ {
		c := value[i]
		if c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '.' || c == '_' || c == '-' {
			continue
		}
		return false
	}
	first := value[0]
	return first >= 'a' && first <= 'z' || first >= 'A' && first <= 'Z' || first >= '0' && first <= '9'
}

func deriveKey(master []byte, purpose string) [sha256.Size]byte {
	mac := hmac.New(sha256.New, master)
	_, _ = mac.Write([]byte(keyDerivationDomain))
	_, _ = mac.Write([]byte{0})
	_, _ = mac.Write([]byte(purpose))
	var derived [sha256.Size]byte
	copy(derived[:], mac.Sum(nil))
	return derived
}

func signMAC(key [sha256.Size]byte, domain string, payload []byte) [sha256.Size]byte {
	mac := hmac.New(sha256.New, key[:])
	_, _ = mac.Write([]byte(domain))
	_, _ = mac.Write([]byte{0})
	_, _ = mac.Write(payload)
	var signature [sha256.Size]byte
	copy(signature[:], mac.Sum(nil))
	return signature
}

func splitCompactToken(token string) (string, []byte, []byte, error) {
	if len(token) == 0 || len(token) > maxCompactTokenBytes {
		return "", nil, nil, ErrMalformed
	}
	parts := strings.Split(token, ".")
	if len(parts) != 3 || !isKeyID(parts[0]) || parts[1] == "" || parts[2] == "" {
		return "", nil, nil, ErrMalformed
	}
	payload, err := base64.RawURLEncoding.Strict().DecodeString(parts[1])
	if err != nil || len(payload) == 0 || len(payload) > maxCompactTokenBytes {
		return "", nil, nil, ErrMalformed
	}
	signature, err := base64.RawURLEncoding.Strict().DecodeString(parts[2])
	if err != nil || len(signature) != sha256.Size {
		return "", nil, nil, ErrMalformed
	}
	return parts[0], payload, signature, nil
}

func decodeCanonicalJSON(payload []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return fmt.Errorf("%w: decode signed payload", ErrMalformed)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return fmt.Errorf("%w: trailing signed payload data", ErrMalformed)
	}
	return nil
}
