// Package providerexchange implements the privacy-minimal cryptographic
// envelope used by the Not Human Search provider exchange.
//
// The signed payloads intentionally contain only NHS-generated opaque UUIDs,
// controlled enums, timestamps, and commercial accounting fields. They have no
// extension map or free-text field where a raw query, contact detail, network
// identifier, or claimed agent/principal identity could be placed.
package providerexchange

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
	"time"
)

const (
	// AttributionTokenVersion is the only attribution-token version accepted by
	// this package. Version changes must use a new signing domain.
	AttributionTokenVersion = 1

	// OutcomeReceiptVersion is the only outcome-receipt version accepted by
	// this package. Version changes must use a new signing domain.
	OutcomeReceiptVersion = 1
	DefaultSigningKeyID   = "nhs-provider-signing-v1"

	// AllowedClockSkew tolerates small clock differences while still rejecting
	// tokens and receipts whose trusted timestamp is materially in the future.
	AllowedClockSkew = 2 * time.Minute

	maxCompactTokenBytes      = 4096
	nonceBytes                = 24
	maxPreviousSigningKeys    = 64
	minimumSigningSecretBytes = 32

	keyDerivationDomain = "nothumansearch/provider-exchange/key-derivation/v1"
	attributionDomain   = "nothumansearch/provider-exchange/attribution-token/v1"
	outcomeDomain       = "nothumansearch/provider-exchange/outcome-receipt/v1"
)

var (
	ErrSecretRequired   = errors.New("provider exchange signing secret required")
	ErrInvalidClaims    = errors.New("invalid signed claims")
	ErrMalformed        = errors.New("malformed signed value")
	ErrInvalidSignature = errors.New("invalid signature")
	ErrUnknownKeyID     = errors.New("unknown provider exchange signing key")
	ErrExpired          = errors.New("signed value expired")
	ErrNotYetValid      = errors.New("signed value is not yet valid")
)

// Outcome is a controlled provider-reported result. It cannot carry free text.
type Outcome string

const (
	OutcomeAccepted  Outcome = "accepted"
	OutcomeActivated Outcome = "activated"
	OutcomeConverted Outcome = "converted"
	OutcomeRejected  Outcome = "rejected"
	OutcomeDuplicate Outcome = "duplicate"
	OutcomeInvalid   Outcome = "invalid"
)

// ChargeStatus says how ChargedMinor affected the provider account. The amount
// is always non-negative; the status supplies the direction.
type ChargeStatus string

const (
	ChargeStatusCharged  ChargeStatus = "charged"
	ChargeStatusCredited ChargeStatus = "credited"
	ChargeStatusNone     ChargeStatus = "none"
)

// AttributionClaims is the complete attribution-token payload. TicketID and
// OfferID must be canonical UUIDs generated by NHS storage. Nonce is random,
// URL-safe entropy and must not be derived from a person, query, request, IP,
// user agent, or alleged agent identity. Times are Unix seconds in UTC.
type AttributionClaims struct {
	Version   int    `json:"v"`
	KeyID     string `json:"kid"`
	TicketID  string `json:"ticket_id"`
	OfferID   string `json:"offer_id"`
	IssuedAt  int64  `json:"issued_at"`
	ExpiresAt int64  `json:"expires_at"`
	Nonce     string `json:"nonce"`
}

// OutcomeReceipt is the complete signed receipt payload. ReceiptID,
// ProviderEventID, TicketID, and OfferID must be NHS-generated canonical UUIDs;
// raw provider idempotency keys must be hashed or mapped to an NHS UUID before
// this type is populated. Currency is an ISO-4217 alpha-3 code in lowercase.
// Times are Unix seconds in UTC.
type OutcomeReceipt struct {
	Version            int          `json:"v"`
	KeyID              string       `json:"kid"`
	ReceiptID          string       `json:"receipt_id"`
	TicketID           string       `json:"ticket_id"`
	OfferID            string       `json:"offer_id"`
	NHSEventID         string       `json:"nhs_event_id"`
	Outcome            Outcome      `json:"outcome"`
	ProviderReportedAt int64        `json:"provider_reported_at"`
	RecordedAt         int64        `json:"recorded_at"`
	ExpiresAt          int64        `json:"expires_at"`
	ChargedMinor       int64        `json:"charged_minor"`
	Currency           string       `json:"currency"`
	ChargeStatus       ChargeStatus `json:"charge_status"`
}

type signingKeyMaterial struct {
	attributionKey [sha256.Size]byte
	outcomeKey     [sha256.Size]byte
}

// Signer derives independent attribution and outcome keys from a dedicated
// provider-exchange signing secret. A bounded keyring lets a rotated active key
// coexist with retained previous keys, so outstanding tickets and historical
// receipts do not silently fail verification after rotation.
type Signer struct {
	activeKeyID string
	keys        map[string]signingKeyMaterial
}

// NewSigner is the single-key constructor used by focused tests and simple
// deployments. Production can use NewSignerKeyring to retain previous keys.
func NewSigner(secret string) (*Signer, error) {
	return NewSignerKeyring(DefaultSigningKeyID, secret, nil)
}

// NewSignerKeyring constructs a signer with one active key and a bounded set of
// previous verification keys. Production startup separately rejects removal of
// any key ID still referenced by an attribution token or outcome receipt. Key
// IDs are public version labels; secret values are never retained after
// domain-specific subkeys are derived.
func NewSignerKeyring(activeKeyID, activeSecret string, previous map[string]string) (*Signer, error) {
	activeKeyID = strings.TrimSpace(activeKeyID)
	if !isKeyID(activeKeyID) || len([]byte(activeSecret)) < minimumSigningSecretBytes || strings.TrimSpace(activeSecret) == "" {
		return nil, ErrSecretRequired
	}
	if len(previous) > maxPreviousSigningKeys {
		return nil, fmt.Errorf("%w: too many previous signing keys", ErrInvalidClaims)
	}
	keys := make(map[string]signingKeyMaterial, len(previous)+1)
	add := func(keyID, secret string) error {
		keyID = strings.TrimSpace(keyID)
		if !isKeyID(keyID) || len([]byte(secret)) < minimumSigningSecretBytes || strings.TrimSpace(secret) == "" {
			return ErrSecretRequired
		}
		if _, exists := keys[keyID]; exists {
			return fmt.Errorf("%w: duplicate signing key id", ErrInvalidClaims)
		}
		keys[keyID] = signingKeyMaterial{
			attributionKey: deriveKey([]byte(secret), attributionDomain),
			outcomeKey:     deriveKey([]byte(secret), outcomeDomain),
		}
		return nil
	}
	if err := add(activeKeyID, activeSecret); err != nil {
		return nil, err
	}
	for keyID, secret := range previous {
		if err := add(keyID, secret); err != nil {
			return nil, err
		}
	}
	return &Signer{activeKeyID: activeKeyID, keys: keys}, nil
}

func (s *Signer) ActiveKeyID() string {
	if s == nil {
		return ""
	}
	return s.activeKeyID
}

// SupportsKeyID reports only whether verification material for a public key ID
// is loaded. It never exposes derived or configured secret material.
func (s *Signer) SupportsKeyID(keyID string) bool {
	if s == nil {
		return false
	}
	_, ok := s.keys[strings.TrimSpace(keyID)]
	return ok
}

// NewNonce returns random URL-safe entropy suitable for AttributionClaims.
// It contains no padding and is independent of request or user data.
func NewNonce() (string, error) {
	raw := make([]byte, nonceBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate attribution nonce: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// NewAttributionClaims creates the fixed attribution payload and a random
// nonce. The caller chooses a short, purpose-appropriate expiry.
func NewAttributionClaims(ticketID, offerID string, issuedAt, expiresAt time.Time) (AttributionClaims, error) {
	return NewAttributionClaimsForKey(DefaultSigningKeyID, ticketID, offerID, issuedAt, expiresAt)
}

func NewAttributionClaimsForKey(keyID, ticketID, offerID string, issuedAt, expiresAt time.Time) (AttributionClaims, error) {
	nonce, err := NewNonce()
	if err != nil {
		return AttributionClaims{}, err
	}
	claims := AttributionClaims{
		Version:   AttributionTokenVersion,
		KeyID:     strings.TrimSpace(keyID),
		TicketID:  ticketID,
		OfferID:   offerID,
		IssuedAt:  issuedAt.Unix(),
		ExpiresAt: expiresAt.Unix(),
		Nonce:     nonce,
	}
	if err := validateAttributionStructure(claims); err != nil {
		return AttributionClaims{}, err
	}
	return claims, nil
}

// SignAttribution returns base64url(payload) + "." + base64url(HMAC). The
// result is safe to place in an action URL query parameter without padding.
func (s *Signer) SignAttribution(claims AttributionClaims) (string, error) {
	if s == nil {
		return "", ErrSecretRequired
	}
	if claims.KeyID == "" {
		claims.KeyID = s.activeKeyID
	}
	keys, ok := s.keys[claims.KeyID]
	if !ok {
		return "", ErrUnknownKeyID
	}
	payload, err := canonicalAttribution(claims)
	if err != nil {
		return "", err
	}
	signature := signMAC(keys.attributionKey, attributionDomain, payload)
	return claims.KeyID + "." + base64.RawURLEncoding.EncodeToString(payload) + "." +
		base64.RawURLEncoding.EncodeToString(signature[:]), nil
}

// VerifyAttribution verifies the immutable claims and then applies their short
// authorization window. Callers must separately enforce ticket state and
// outcome idempotency.
func (s *Signer) VerifyAttribution(token string, now time.Time) (AttributionClaims, error) {
	claims, err := s.VerifyAttributionSignature(token)
	if err != nil {
		return AttributionClaims{}, err
	}
	if err := validateAttributionTime(claims, now); err != nil {
		return AttributionClaims{}, err
	}
	return claims, nil
}

// VerifyAttributionSignature authenticates immutable attribution claims but
// deliberately does not apply their authorization window. This is only for
// resolving an already charged ticket with a later invalid/duplicate credit;
// it must never authorize a redirect, positive outcome, or new charge.
func (s *Signer) VerifyAttributionSignature(token string) (AttributionClaims, error) {
	if s == nil {
		return AttributionClaims{}, ErrSecretRequired
	}
	keyID, payload, providedMAC, err := splitCompactToken(token)
	if err != nil {
		return AttributionClaims{}, err
	}
	keys, ok := s.keys[keyID]
	if !ok {
		return AttributionClaims{}, ErrUnknownKeyID
	}
	expectedMAC := signMAC(keys.attributionKey, attributionDomain, payload)
	if subtle.ConstantTimeCompare(providedMAC, expectedMAC[:]) != 1 {
		return AttributionClaims{}, ErrInvalidSignature
	}
	var claims AttributionClaims
	if err := decodeCanonicalJSON(payload, &claims); err != nil {
		return AttributionClaims{}, err
	}
	if claims.KeyID != keyID {
		return AttributionClaims{}, ErrInvalidSignature
	}
	canonical, err := canonicalAttribution(claims)
	if err != nil {
		return AttributionClaims{}, err
	}
	if !bytes.Equal(payload, canonical) {
		return AttributionClaims{}, fmt.Errorf("%w: non-canonical attribution payload", ErrMalformed)
	}
	return claims, nil
}

// CanonicalOutcomeReceipt returns the exact deterministic bytes covered by an
// outcome signature. Field order is the OutcomeReceipt declaration order;
// values are compact JSON with no whitespace or trailing newline.
func CanonicalOutcomeReceipt(receipt OutcomeReceipt) ([]byte, error) {
	if err := validateOutcomeStructure(receipt); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(receipt)
	if err != nil {
		return nil, fmt.Errorf("%w: encode outcome receipt: %v", ErrMalformed, err)
	}
	return payload, nil
}

// SignOutcomeReceipt returns canonical receipt JSON and its unpadded base64url
// signature separately so both can be persisted after transaction-derived
// charging fields are known.
func (s *Signer) SignOutcomeReceipt(receipt OutcomeReceipt) (canonical string, signature string, err error) {
	if s == nil {
		return "", "", ErrSecretRequired
	}
	if receipt.KeyID == "" {
		receipt.KeyID = s.activeKeyID
	}
	keys, ok := s.keys[receipt.KeyID]
	if !ok {
		return "", "", ErrUnknownKeyID
	}
	payload, err := CanonicalOutcomeReceipt(receipt)
	if err != nil {
		return "", "", err
	}
	mac := signMAC(keys.outcomeKey, outcomeDomain, payload)
	return string(payload), base64.RawURLEncoding.EncodeToString(mac[:]), nil
}

// VerifyOutcomeReceipt authenticates a canonical receipt in constant time,
// rejects added/unknown fields and non-canonical JSON, then applies expiry and
// future-timestamp checks.
func (s *Signer) VerifyOutcomeReceipt(canonical, signature string, now time.Time) (OutcomeReceipt, error) {
	receipt, err := s.VerifyOutcomeReceiptSignature(canonical, signature)
	if err != nil {
		return OutcomeReceipt{}, err
	}
	if err := validateOutcomeTime(receipt, now); err != nil {
		return OutcomeReceipt{}, err
	}
	return receipt, nil
}

// VerifyOutcomeReceiptSignature authenticates immutable receipt contents but
// deliberately does not apply the receipt freshness window. Public callers can
// report cryptographic validity separately from freshness and current online
// ticket/accounting state.
func (s *Signer) VerifyOutcomeReceiptSignature(canonical, signature string) (OutcomeReceipt, error) {
	if s == nil {
		return OutcomeReceipt{}, ErrSecretRequired
	}
	if len(canonical) == 0 || len(canonical) > maxCompactTokenBytes {
		return OutcomeReceipt{}, ErrMalformed
	}
	providedMAC, err := base64.RawURLEncoding.Strict().DecodeString(signature)
	if err != nil || len(providedMAC) != sha256.Size {
		return OutcomeReceipt{}, ErrMalformed
	}
	payload := []byte(canonical)
	var receipt OutcomeReceipt
	if err := decodeCanonicalJSON(payload, &receipt); err != nil {
		return OutcomeReceipt{}, err
	}
	keys, ok := s.keys[receipt.KeyID]
	if !ok {
		return OutcomeReceipt{}, ErrUnknownKeyID
	}
	expectedMAC := signMAC(keys.outcomeKey, outcomeDomain, payload)
	if subtle.ConstantTimeCompare(providedMAC, expectedMAC[:]) != 1 {
		return OutcomeReceipt{}, ErrInvalidSignature
	}
	reencoded, err := CanonicalOutcomeReceipt(receipt)
	if err != nil {
		return OutcomeReceipt{}, err
	}
	if !bytes.Equal(payload, reencoded) {
		return OutcomeReceipt{}, fmt.Errorf("%w: non-canonical outcome receipt", ErrMalformed)
	}
	return receipt, nil
}

func canonicalAttribution(claims AttributionClaims) ([]byte, error) {
	if err := validateAttributionStructure(claims); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(claims)
	if err != nil {
		return nil, fmt.Errorf("%w: encode attribution claims: %v", ErrMalformed, err)
	}
	return payload, nil
}

func validateAttributionStructure(claims AttributionClaims) error {
	if claims.Version != AttributionTokenVersion {
		return fmt.Errorf("%w: unsupported attribution version", ErrInvalidClaims)
	}
	if !isKeyID(claims.KeyID) {
		return fmt.Errorf("%w: invalid attribution key id", ErrInvalidClaims)
	}
	if !isCanonicalUUID(claims.TicketID) || !isCanonicalUUID(claims.OfferID) {
		return fmt.Errorf("%w: attribution IDs must be canonical UUIDs", ErrInvalidClaims)
	}
	if claims.IssuedAt <= 0 || claims.ExpiresAt <= claims.IssuedAt {
		return fmt.Errorf("%w: invalid attribution validity window", ErrInvalidClaims)
	}
	if !isBase64URLNonce(claims.Nonce) {
		return fmt.Errorf("%w: invalid attribution nonce", ErrInvalidClaims)
	}
	return nil
}

func validateAttributionTime(claims AttributionClaims, now time.Time) error {
	if now.IsZero() {
		return fmt.Errorf("%w: verification time required", ErrInvalidClaims)
	}
	nowUnix := now.Unix()
	if claims.IssuedAt > now.Add(AllowedClockSkew).Unix() {
		return ErrNotYetValid
	}
	if nowUnix >= claims.ExpiresAt {
		return ErrExpired
	}
	return nil
}

func validateOutcomeStructure(receipt OutcomeReceipt) error {
	if receipt.Version != OutcomeReceiptVersion {
		return fmt.Errorf("%w: unsupported outcome receipt version", ErrInvalidClaims)
	}
	if !isKeyID(receipt.KeyID) {
		return fmt.Errorf("%w: invalid outcome key id", ErrInvalidClaims)
	}
	if !isCanonicalUUID(receipt.ReceiptID) ||
		!isCanonicalUUID(receipt.TicketID) ||
		!isCanonicalUUID(receipt.OfferID) ||
		!isCanonicalUUID(receipt.NHSEventID) {
		return fmt.Errorf("%w: outcome IDs must be canonical UUIDs", ErrInvalidClaims)
	}
	if !validOutcome(receipt.Outcome) {
		return fmt.Errorf("%w: unsupported outcome", ErrInvalidClaims)
	}
	if receipt.ProviderReportedAt <= 0 || receipt.RecordedAt <= 0 || receipt.ExpiresAt <= receipt.RecordedAt {
		return fmt.Errorf("%w: invalid outcome validity window", ErrInvalidClaims)
	}
	if receipt.ProviderReportedAt > receipt.RecordedAt+int64(AllowedClockSkew/time.Second) {
		return fmt.Errorf("%w: provider report occurs after recording", ErrInvalidClaims)
	}
	if receipt.ChargedMinor < 0 {
		return fmt.Errorf("%w: charged_minor must be non-negative", ErrInvalidClaims)
	}
	if receipt.Currency != "usd" {
		return fmt.Errorf("%w: pilot receipt currency must be usd", ErrInvalidClaims)
	}
	switch receipt.ChargeStatus {
	case ChargeStatusCharged, ChargeStatusCredited:
		if receipt.ChargedMinor == 0 {
			return fmt.Errorf("%w: charged or credited receipt requires a positive amount", ErrInvalidClaims)
		}
	case ChargeStatusNone:
		if receipt.ChargedMinor != 0 {
			return fmt.Errorf("%w: uncharged receipt must have zero charged_minor", ErrInvalidClaims)
		}
	default:
		return fmt.Errorf("%w: unsupported charge_status", ErrInvalidClaims)
	}
	return nil
}

func validateOutcomeTime(receipt OutcomeReceipt, now time.Time) error {
	if now.IsZero() {
		return fmt.Errorf("%w: verification time required", ErrInvalidClaims)
	}
	latestAllowed := now.Add(AllowedClockSkew).Unix()
	if receipt.RecordedAt > latestAllowed || receipt.ProviderReportedAt > latestAllowed {
		return ErrNotYetValid
	}
	if now.Unix() >= receipt.ExpiresAt {
		return ErrExpired
	}
	return nil
}

func validOutcome(outcome Outcome) bool {
	switch outcome {
	case OutcomeAccepted, OutcomeActivated, OutcomeConverted, OutcomeRejected, OutcomeDuplicate, OutcomeInvalid:
		return true
	default:
		return false
	}
}

func isCanonicalUUID(value string) bool {
	if len(value) != 36 {
		return false
	}
	for i := 0; i < len(value); i++ {
		switch i {
		case 8, 13, 18, 23:
			if value[i] != '-' {
				return false
			}
		default:
			if !((value[i] >= '0' && value[i] <= '9') || (value[i] >= 'a' && value[i] <= 'f')) {
				return false
			}
		}
	}
	return true
}

func isBase64URLNonce(value string) bool {
	if len(value) != base64.RawURLEncoding.EncodedLen(nonceBytes) {
		return false
	}
	raw, err := base64.RawURLEncoding.Strict().DecodeString(value)
	return err == nil && len(raw) == nonceBytes
}

func isKeyID(value string) bool {
	if len(value) < 3 || len(value) > 64 {
		return false
	}
	for i := 0; i < len(value); i++ {
		c := value[i]
		if c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '.' || c == '_' || c == '-' {
			continue
		}
		return false
	}
	first := value[0]
	return first >= 'a' && first <= 'z' || first >= 'A' && first <= 'Z' || first >= '0' && first <= '9'
}

func deriveKey(master []byte, purpose string) [sha256.Size]byte {
	mac := hmac.New(sha256.New, master)
	_, _ = mac.Write([]byte(keyDerivationDomain))
	_, _ = mac.Write([]byte{0})
	_, _ = mac.Write([]byte(purpose))
	var derived [sha256.Size]byte
	copy(derived[:], mac.Sum(nil))
	return derived
}

func signMAC(key [sha256.Size]byte, domain string, payload []byte) [sha256.Size]byte {
	mac := hmac.New(sha256.New, key[:])
	_, _ = mac.Write([]byte(domain))
	_, _ = mac.Write([]byte{0})
	_, _ = mac.Write(payload)
	var signature [sha256.Size]byte
	copy(signature[:], mac.Sum(nil))
	return signature
}

func splitCompactToken(token string) (string, []byte, []byte, error) {
	if len(token) == 0 || len(token) > maxCompactTokenBytes {
		return "", nil, nil, ErrMalformed
	}
	parts := strings.Split(token, ".")
	if len(parts) != 3 || !isKeyID(parts[0]) || parts[1] == "" || parts[2] == "" {
		return "", nil, nil, ErrMalformed
	}
	payload, err := base64.RawURLEncoding.Strict().DecodeString(parts[1])
	if err != nil || len(payload) == 0 || len(payload) > maxCompactTokenBytes {
		return "", nil, nil, ErrMalformed
	}
	signature, err := base64.RawURLEncoding.Strict().DecodeString(parts[2])
	if err != nil || len(signature) != sha256.Size {
		return "", nil, nil, ErrMalformed
	}
	return parts[0], payload, signature, nil
}

func decodeCanonicalJSON(payload []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return fmt.Errorf("%w: decode signed payload", ErrMalformed)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return fmt.Errorf("%w: trailing signed payload data", ErrMalformed)
	}
	return nil
}
